// Code generated by protoc-gen-go.
// source: Kademlia.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	Kademlia.proto

It has these top-level messages:
	KademliaMessage
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type KademliaMessage struct {
	Label            *string                        `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Senderid         *string                        `protobuf:"bytes,2,req,name=senderid" json:"senderid,omitempty"`
	SenderAddr       *string                        `protobuf:"bytes,3,req,name=senderAddr" json:"senderAddr,omitempty"`
	Lookupcontact    *KademliaMessage_LookupContact `protobuf:"group,4,opt,name=LookupContact" json:"lookupcontact,omitempty"`
	Data             []byte                         `protobuf:"bytes,8,opt,name=data" json:"data,omitempty"`
	Key              *string                        `protobuf:"bytes,9,opt,name=key" json:"key,omitempty"`
	Value            *string                        `protobuf:"bytes,10,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *KademliaMessage) Reset()         { *m = KademliaMessage{} }
func (m *KademliaMessage) String() string { return proto.CompactTextString(m) }
func (*KademliaMessage) ProtoMessage()    {}

func (m *KademliaMessage) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *KademliaMessage) GetSenderid() string {
	if m != nil && m.Senderid != nil {
		return *m.Senderid
	}
	return ""
}

func (m *KademliaMessage) GetSenderAddr() string {
	if m != nil && m.SenderAddr != nil {
		return *m.SenderAddr
	}
	return ""
}

func (m *KademliaMessage) GetLookupcontact() *KademliaMessage_LookupContact {
	if m != nil {
		return m.Lookupcontact
	}
	return nil
}

func (m *KademliaMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *KademliaMessage) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KademliaMessage) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type KademliaMessage_LookupContact struct {
	Id               *string `protobuf:"bytes,5,req,name=id" json:"id,omitempty"`
	Address          *string `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
	Distance         *string `protobuf:"bytes,7,opt,name=distance" json:"distance,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KademliaMessage_LookupContact) Reset()         { *m = KademliaMessage_LookupContact{} }
func (m *KademliaMessage_LookupContact) String() string { return proto.CompactTextString(m) }
func (*KademliaMessage_LookupContact) ProtoMessage()    {}

func (m *KademliaMessage_LookupContact) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *KademliaMessage_LookupContact) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *KademliaMessage_LookupContact) GetDistance() string {
	if m != nil && m.Distance != nil {
		return *m.Distance
	}
	return ""
}

func init() {
}
