// Code generated by protoc-gen-go.
// source: Kademlia.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	Kademlia.proto

It has these top-level messages:
	KademliaMessage
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type KademliaMessage struct {
	Label            *string `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Senderid         *string `protobuf:"bytes,2,req,name=senderid" json:"senderid,omitempty"`
	SenderAddr       *string `protobuf:"bytes,3,req,name=senderAddr" json:"senderAddr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KademliaMessage) Reset()         { *m = KademliaMessage{} }
func (m *KademliaMessage) String() string { return proto.CompactTextString(m) }
func (*KademliaMessage) ProtoMessage()    {}

func (m *KademliaMessage) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *KademliaMessage) GetSenderid() string {
	if m != nil && m.Senderid != nil {
		return *m.Senderid
	}
	return ""
}

func (m *KademliaMessage) GetSenderAddr() string {
	if m != nil && m.SenderAddr != nil {
		return *m.SenderAddr
	}
	return ""
}

func init() {
}
